export {default as Home} from './Home/Home';
export {default as About} from './About/About';
export {default as AdmissionInfo} from './AdmissionInfo/AdmissionInfo';
export {default as Contact} from './Contact/Contact';
export {default as Opportunities} from './Opportunities/Opportunities';
export {default as Results} from './Results/Results';
export {default as Students} from './Students/Students';
export {default as Academic} from './Academic/Academic';
export {default as Others} from './Others/Others';